# Generated by Django 4.2.11 on 2024-04-01 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('seq', models.BigAutoField(help_text='일련번호(PK)', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='이름', max_length=64)),
                ('create_by', models.CharField(help_text='생성자', max_length=64)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('update_by', models.CharField(help_text='수정자', max_length=64)),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-seq'],
            },
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('seq', models.BigAutoField(help_text='일련번호(PK)', primary_key=True, serialize=False)),
                ('labels', models.CharField(help_text='라벨', max_length=256)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('user_seq', models.ForeignKey(db_column='user_seq', db_constraint=False, help_text='사용자 일련번호(FK)', on_delete=django.db.models.deletion.PROTECT, to='apps.users')),
            ],
            options={
                'db_table': 'labels',
                'ordering': ['-seq'],
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('seq', models.BigAutoField(help_text='일련번호(PK)', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='이름', max_length=256)),
                ('image_url', models.CharField(help_text='이미지 URL', max_length=256, null=True)),
                ('email', models.CharField(help_text='이메일', max_length=256)),
                ('phone_number', models.CharField(help_text='전화번호', max_length=256)),
                ('address', models.CharField(help_text='주소', max_length=256, null=True)),
                ('web_site', models.CharField(help_text='웹사이트', max_length=256, null=True)),
                ('company', models.CharField(help_text='회사', max_length=256, null=True)),
                ('position', models.CharField(help_text='직책', max_length=256, null=True)),
                ('birthday', models.DateTimeField(auto_now_add=True, help_text='생일', null=True)),
                ('memo', models.CharField(help_text='메모', max_length=1000, null=True)),
                ('create_by', models.CharField(help_text='생성자', max_length=64)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('update_by', models.CharField(help_text='수정자', max_length=64)),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('user_seq', models.ForeignKey(db_column='user_seq', db_constraint=False, help_text='사용자 일련번호(FK)', on_delete=django.db.models.deletion.PROTECT, to='apps.users')),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['-seq'],
            },
        ),
        migrations.CreateModel(
            name='ContactLabels',
            fields=[
                ('seq', models.BigAutoField(help_text='일련번호(PK)', primary_key=True, serialize=False)),
                ('contact_seq', models.ForeignKey(db_column='contact_seq', db_constraint=False, help_text='주소록 일련번호(FK)', on_delete=django.db.models.deletion.PROTECT, to='apps.contacts')),
                ('label_seq', models.ForeignKey(db_column='label_seq', db_constraint=False, help_text='라벨 일련번호(FK)', on_delete=django.db.models.deletion.PROTECT, to='apps.labels')),
            ],
            options={
                'db_table': 'contact_labels',
                'ordering': ['-seq'],
            },
        ),
    ]
